version: "3.6"

services:
    news-kibana-crawler:
        container_name: news-kibana-crawler
        image: node:16-alpine3.12
        restart: always
        # env_file: .env
        ports:
            - 3000:3000
        volumes:
            - ./:/src
        working_dir: /src
        extra_hosts:
            - "host.docker.internal:host-gateway"
        command:
            - /bin/sh
            - -c
            - |
                npm i
                npm run start